# Generated by Django 4.1.1 on 2022-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="category",
            new_name="categories",
        ),
    ]
