# Generated by Django 4.1.1 on 2022-09-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_category_book_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=12.34, max_digits=20),
        ),
    ]
