# Generated by Django 4.1.1 on 2022-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
