# Generated by Django 4.1 on 2022-08-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_alter_snippet_highlighted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="highlighted",
            field=models.TextField(blank=True, default=""),
        ),
    ]
